/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.kangacoders.launcher;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;


@Kroll.module(name="Launcher", id="com.kangacoders.launcher")
public class LauncherModule extends KrollModule
{
	private static final String LCAT = "LauncherModule";
	private static final boolean DBG = TiConfig.LOGD;

	public LauncherModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
	}

	@Kroll.method
	public void openPackage(String packageName)
	{
		TiApplication context = TiApplication.getInstance();
		Activity activity = context.getCurrentActivity();

		Intent intent = activity.getPackageManager().getLaunchIntentForPackage(packageName);
    if (intent != null) {
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        activity.startActivity(intent);
    } else {
        intent = new Intent(Intent.ACTION_VIEW);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        intent.setData(Uri.parse("market://details?id=" + packageName));
        activity.startActivity(intent);
    }
	}

}

